In [81]:
import numpy as np
a1= np.arange(1, 10).reshape(3, 3)
a2= np.arange(41, 50).reshape(3, 3)
a3= np.arange(10, 16).reshape(3, 2)
a4= np.arange(20, 26).reshape(2, 3)

## Concatenation
- axis 1 means column will extend means vertical stacking
- axis 0 means row will extend means row stacking

In [82]:


print(a1)
print(a2)
print(np.concatenate((a1, a2), axis=1))
print(np.concatenate((a1, a2), axis=0))

print("\n")
print(a3)
print(a4)
#all the dimensions must be the same except the dimension along which you are concatenating
#print(np.concatenate((a3, a4), axis=1))
#print(np.concatenate((a3, a4), axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[41 42 43]
 [44 45 46]
 [47 48 49]]
[[ 1  2  3 41 42 43]
 [ 4  5  6 44 45 46]
 [ 7  8  9 47 48 49]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [41 42 43]
 [44 45 46]
 [47 48 49]]


[[10 11]
 [12 13]
 [14 15]]
[[20 21 22]
 [23 24 25]]


### Vstack and Hstack
The first positonal argument is a tuple of the matrices to be passed hence np.vstack( (tuple of array ), )


In [83]:
print("Vertical Stack")
vs=np.vstack((a1, a2))
print(vs)

print("\nHorizontal Stack")
hs=np.hstack((a1, a2))
print(hs)

Vertical Stack
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [41 42 43]
 [44 45 46]
 [47 48 49]]

Horizontal Stack
[[ 1  2  3 41 42 43]
 [ 4  5  6 44 45 46]
 [ 7  8  9 47 48 49]]


## Split
- split
- vsplit
- hsplit

in split the second argument has 2 types
- if we give a single value it will divide the array into n sections
- if we pass a tuple of values then it will divide it into [0:a]+[a:b]+[c:]...


In [84]:
print(hs)

print("\n split in 3 sections")
print(np.split(hs, 3, axis=1))

print("\n\nsplit in [0:2]+[2:]")
print(np.split(hs,(2,), axis=1))


print("\n\nsplit in [0:2]+[2:6]+[6:]")
print(np.split(hs,(2,6), axis=1))
# print(type(sp1), len(sp1))
#print(sp1[0])
#print(sp1[1])
#print(sp1[2])
# print("\n")
# np.split(a1, 3, axis=0)


[[ 1  2  3 41 42 43]
 [ 4  5  6 44 45 46]
 [ 7  8  9 47 48 49]]

 split in 3 sections
[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[ 3, 41],
       [ 6, 44],
       [ 9, 47]]), array([[42, 43],
       [45, 46],
       [48, 49]])]


split in [0:2]+[2:]
[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[ 3, 41, 42, 43],
       [ 6, 44, 45, 46],
       [ 9, 47, 48, 49]])]


split in [0:2]+[2:6]+[6:]
[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[ 3, 41, 42, 43],
       [ 6, 44, 45, 46],
       [ 9, 47, 48, 49]]), array([], shape=(3, 0), dtype=int64)]


#### Trigonometetric functions and log functions

In [85]:
a=np.array([0,30,60,90])
print(np.cos(a*np.pi/180))
print(np.tan(a*np.pi/180))
print(np.sin(a*np.pi/180))
print(np.log2(2))
print(np.log10(10))
print(np.log(10))


[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]
[0.        0.5       0.8660254 1.       ]
1.0
1.0
2.302585092994046


## Numpy Broadcasting
 
Array can be treated as normal variable and can do normal calculation

In [86]:
print("\n", a1, "\n\n", a2)
print("\n")
print(a1+2*a2)
print("\n")
print(a1*a2)
print("\n")
print(a1/a2)
print("\n")
print(a1.dot(a2)) #matrix multiplication


 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[41 42 43]
 [44 45 46]
 [47 48 49]]


[[ 83  86  89]
 [ 92  95  98]
 [101 104 107]]


[[ 41  84 129]
 [176 225 276]
 [329 384 441]]


[[0.02439024 0.04761905 0.06976744]
 [0.09090909 0.11111111 0.13043478]
 [0.14893617 0.16666667 0.18367347]]


[[ 270  276  282]
 [ 666  681  696]
 [1062 1086 1110]]


## Selection
Suppose a numpy array has of dim 4x5, 
we can perfom slicing for each dimension
i.e a[row_slice, column_slice]

In [87]:
print(a1)

print("\na1[1:2, 1:2]\n",a1[1:2, 1:2])
print("\na1[1:, 1:]\n",a1[1:, 1:])

print("\na1[::-1,::-1]\n",a1[::-1,::-1])
print("\na1[::2,::2]\n",a1[::2,::2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]

a1[1:2, 1:2]
 [[5]]

a1[1:, 1:]
 [[5 6]
 [8 9]]

a1[::-1,::-1]
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

a1[::2,::2]
 [[1 3]
 [7 9]]


In [89]:
a=np.random.randint(-5,5,(4,6))
print(a)

[[ 0 -2 -5 -4  2 -1]
 [ 3  1  0 -3 -4 -5]
 [-1 -2 -3 -3  2 -1]
 [ 1  1  3 -5 -2 -2]]


In [100]:
print(a<0)
print()
print(a[a<0])
print()
print(a[(a%2==0) & (a>0)])
print()
print(a[(a%2==0) | ((a>2) & (a%2!=0) )])

[[False  True  True  True False  True]
 [False False False  True  True  True]
 [ True  True  True  True False  True]
 [False False False  True  True  True]]

[-2 -5 -4 -1 -3 -4 -5 -1 -2 -3 -3 -1 -5 -2 -2]

[2 2]

[ 0 -2 -4  2  3  0 -4 -2  2  3 -2 -2]
