In [1]:
import numpy as np

In [2]:
a=np.array([11,1.2])
b=np.array([[1,2],[3,4],[5,6]])
a

array([11. ,  1.2])

In [3]:
print(a.shape)
print(b.shape)
print(a.ndim)
print(a.dtype)

(2,)
(3, 2)
1
float64


In [4]:
type(a)

numpy.ndarray

In [5]:
l1=list(range(1000))
%timeit [x**2 for x in l1]

57.4 μs ± 2.12 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [6]:
l2=np.arange(1000)
%timeit l2**2

1.02 μs ± 89.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
a1 = np.zeros((5, 6), dtype='int64')
a2=np.ones((2,3))
a3=np.full((4,5),fill_value=13)

In [13]:
print(a1)
print(a2)
print(a3)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


In [15]:
n1=np.array([[1,2,3],[4,5,6]])
print(n1)
n1[1,1]=100
print(n1)

[[1 2 3]
 [4 5 6]]
[[  1   2   3]
 [  4 100   6]]
