In [2]:
import numpy as np

1. Create an array of zeros with shape (5, 6) and datatype int64

In [3]:
a1 = np.zeros((5, 6), dtype='int64')
print("\nArray a1:\n", a1)


Array a1:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


2. Create an array of ones with shape (2, 3)

In [4]:
a2 = np.ones((2, 3))
print("\nArray a2:\n", a2)


Array a2:
 [[1. 1. 1.]
 [1. 1. 1.]]


3. Create an array with shape (4, 5) and fill it with the value 13

In [5]:
a3 = np.full((4, 5), fill_value=13)
print("\nArray a3:\n", a3)


Array a3:
 [[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


Creates a empty value with garbage values

In [6]:
a4=np.empty((4,5))
print("Empty a4:\n", a4)

Empty a4:
 [[2.05088626e-316 0.00000000e+000 4.84230182e-317 6.94863137e-310
  4.85008830e-317]
 [4.84474053e-317 6.94863129e-310 4.85584317e-317 2.05799053e-316
  6.94863141e-310]
 [4.85401711e-317 4.85713565e-317 4.85720679e-317 6.94863136e-310
  6.94863129e-310]
 [6.94863129e-310 4.83896984e-317 4.85964946e-317 4.85969689e-317
  6.94863129e-310]]


Prints a indenty matix with default value float 1.

In [7]:
a5=np.eye(4)
print("\nIndentity matrix\n",a5)


a5=np.eye(4,2)
print("\nRectangular indentity matrix\n",a5)


Indentity matrix
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Rectangular indentity matrix
 [[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


diag prints the diagonal values in a array 
- <0 lower diagonal of main diag
- \>0 upper diagonal of main diag
- 0 default value

In [8]:
test=np.arange(6).reshape(3,2)
print("\nTest\n",test)

a6=np.diag(test)
print("\ndiag of test:")
print(a6)

a6=np.diag(test,-1)
print("\nupper diag of test:")
print(a6)

a6=np.diag(test,1)
print("\nLower diag of test:")
print(a6)


Test
 [[0 1]
 [2 3]
 [4 5]]

diag of test:
[0 3]

upper diag of test:
[2 5]

Lower diag of test:
[1]


flipup flips the array upside down
fliplr flips the array left to right

In [9]:
a7=np.flipud(test)
print("\nflip up of test")
print(a7)

a8=np.fliplr(test)
print("\nflip left right of test")
print(a8)

a9=np.diag(np.fliplr(np.eye(2)))
print("\nRight diagonal")
print(a9)


flip up of test
[[4 5]
 [2 3]
 [0 1]]

flip left right of test
[[1 0]
 [3 2]
 [5 4]]

Right diagonal
[0. 0.]


axis=0 means we are taking in account of each indivdual rows
> [[r1],[r2],...[rn]] => [[rn],[r(n-1)],....[r1]]

axis=1 means we are taking in account of each individual colums
> [c1,c2,...cn] => [[cn],[c(n-1)],...[c1]]

In [21]:
test2=np.arange(1,13).reshape(4,3)
print("\ntest",test2)

a10=np.flip(test2,axis=0)
print("\nflip axis 0",a10)

a11=np.flip(test2,axis=1)
print("\nflip axis 1",a11)

a12=np.transpose(test2)
print("\ntranspose\n",a12)

a12=np.rot90(test2)
print("\nrotate 90\n",a12)

print("\n",test.T)


test [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

flip axis 0 [[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]

flip axis 1 [[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]

transpose
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

rotate 90
 [[ 3  6  9 12]
 [ 2  5  8 11]
 [ 1  4  7 10]]

 [[0 2 4]
 [1 3 5]]


Reshape array

In [11]:
#a13=test.reshape(

if we give arr.reshape(dim,negative value) then the other dimension will be autocomputed by numpy

In [12]:
print("\n arrays:\n",test2.reshape(2,-1),"\n",test2.reshape(12,-1))


 arrays:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [13]:
print("\n arrays:\n",test2.reshape(-1,2),"\n",test2.reshape(-1,12))


 arrays:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]]


To flatten the matrix into one vector 
- reshape changes the original array with 
- ravel is a function that returns a view of the orignal 
- changes the orignal array

In [14]:
print(test2.reshape(12,))
print(np.ravel(test2))
print(test2.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


linspace : it arranges a range of array into equidistant elements
- start stop step are the values
- endpoint denotes if the endpoint is inclusive or not
- restep will display the gap between all elements

In [15]:
print(np.linspace(0,10,5))
print(np.linspace(0,10,5,endpoint=False))
print(np.linspace(0,10,5,retstep=True))
print(np.linspace(5,0,5,retstep=True))

print("Big array")
print(np.linspace(0,5,10000,retstep=True))  #will not display all elements

[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]
(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)
(array([5.  , 3.75, 2.5 , 1.25, 0.  ]), -1.25)
Big array
(array([0.00000000e+00, 5.00050005e-04, 1.00010001e-03, ...,
       4.99899990e+00, 4.99949995e+00, 5.00000000e+00]), 0.0005000500050005)


Random Function :<br>
probability mass function - discrete function<br>
probability density function - continous function<br>

In [16]:
print(int(np.random.random()*10))
print(np.random.random((2,3)))
print(np.random.random((2,3,4)))

4
[[0.437279   0.5986565  0.55564961]
 [0.09951558 0.29911171 0.05533303]]
[[[0.06670686 0.04485375 0.17329738 0.00409113]
  [0.20506871 0.3860595  0.7962353  0.88697228]
  [0.74219861 0.42869842 0.31556289 0.56810516]]

 [[0.21741209 0.93001341 0.03255263 0.89682925]
  [0.74218596 0.88935112 0.29350804 0.22908207]
  [0.98696412 0.18728612 0.11130738 0.6063488 ]]]


#### Binomial distribution and Normal distribution of array 
**Binomial** : 
- takes n:trials
- takes p success rate
- take the no of occurence

**Normal**
- loc (centreness)
- scale (std)
- size of result


In [17]:
a=np.random.binomial(10000,0.5)
print(a)

b=np.random.normal(0,10,10)
print(b)

print(np.random.randint(0,10,10))
print(np.random.randint(0,10,(2,3)))

4977
[ 13.27009927  19.17806638   6.3484875   -3.48709862  18.32562067
 -21.92825222 -10.15019639  12.34448146  -4.51272124  -2.44562032]
[0 5 3 7 2 1 7 7 5 8]
[[2 6 5]
 [8 4 8]]


Row and column wise array elements operations

In [18]:
a=(np.random.randint(0,10,(2,3)))
print(a)
print("\nmin :",np.min(a))
print("row min :",np.min(a,axis=1)) #row wise
print("col min :",np.min(a,axis=0)) #column wise

print("\nmax :",np.max(a))
print("row max :",np.max(a,axis=1))
print("col max :",np.max(a,axis=0))

print("\nmean :",np.mean(a))
print("row mean :",np.mean(a,axis=1))
print("col mean :",np.mean(a,axis=0))

print("\nstd :",np.std(a))
print("row std :",np.std(a,axis=1))
print("col std :",np.std(a,axis=0))

print("\nsum :",np.sum(a))
print("row sum :",np.sum(a,axis=1))
print("col sum :",np.sum(a,axis=0))

[[6 0 7]
 [9 4 7]]

min : 0
row min : [0 4]
col min : [6 0 7]

max : 9
row max : [7 9]
col max : [9 4 7]

mean : 5.5
row mean : [4.33333333 6.66666667]
col mean : [7.5 2.  7. ]

std : 2.8722813232690143
row std : [3.09120617 2.05480467]
col std : [1.5 2.  0. ]

sum : 33
row sum : [13 20]
col sum : [15  4 14]


passes the index of the max value, of total or row wise or column wise

In [19]:
print(a)
print(np.argmax(a))
print(np.argmax(a,axis=1))
print(np.argmax(a,axis=0))


[[6 0 7]
 [9 4 7]]
3
[2 0]
[1 1 0]
