In [1]:
import numpy as np

1. Create an array of zeros with shape (5, 6) and datatype int64

In [2]:
a1 = np.zeros((5, 6), dtype='int64')
print("\nArray a1:\n", a1)


Array a1:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


2. Create an array of ones with shape (2, 3)

In [3]:
a2 = np.ones((2, 3))
print("\nArray a2:\n", a2)


Array a2:
 [[1. 1. 1.]
 [1. 1. 1.]]


3. Create an array with shape (4, 5) and fill it with the value 13

In [4]:
a3 = np.full((4, 5), fill_value=13)
print("\nArray a3:\n", a3)


Array a3:
 [[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


Creates a empty value with garbage values

In [5]:
a4=np.empty((4,5))
print("Empty a4:\n", a4)

Empty a4:
 [[1.21146438e-316 0.00000000e+000 2.35525473e-315 0.00000000e+000
  1.07034138e-296]
 [2.10966031e-321 1.65430819e-310 3.14509217e-234 0.00000000e+000
  3.59383351e-320]
 [0.00000000e+000 1.26035873e-300 1.39067116e-309 8.39461648e-311
  8.40980319e-172]
 [0.00000000e+000 0.00000000e+000 9.06112796e-312 2.04706931e-306
  7.95751304e-312]]


Prints a indenty matix with default value float 1.

In [6]:
a5=np.eye(4)
print("\nIndentity matrix\n",a5)


a5=np.eye(4,2)
print("\nRectangular indentity matrix\n",a5)


Indentity matrix
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Rectangular indentity matrix
 [[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


diag prints the diagonal values in a array 
- <0 lower diagonal of main diag
- \>0 upper diagonal of main diag
- 0 default value

In [7]:
test=np.arange(6).reshape(3,2)
print("\nTest\n",test)

a6=np.diag(test)
print("\ndiag of test:")
print(a6)

a6=np.diag(test,-1)
print("\nupper diag of test:")
print(a6)

a6=np.diag(test,1)
print("\nLower diag of test:")
print(a6)


Test
 [[0 1]
 [2 3]
 [4 5]]

diag of test:
[0 3]

upper diag of test:
[2 5]

Lower diag of test:
[1]


flipup flips the array upside down
fliplr flips the array left to right

In [8]:
a7=np.flipud(test)
print("\nflip up of test")
print(a7)

a8=np.fliplr(test)
print("\nflip left right of test")
print(a8)

a9=np.diag(np.fliplr(np.eye(2)))
print("\nRight diagonal")
print(a9)


flip up of test
[[4 5]
 [2 3]
 [0 1]]

flip left right of test
[[1 0]
 [3 2]
 [5 4]]

Right diagonal
[0. 0.]


axis=0 means we are taking in account of each indivdual rows
> [[r1],[r2],...[rn]] => [[rn],[r(n-1)],....[r1]]

axis=1 means we are taking in account of each individual colums
> [c1,c2,...cn] => [[cn],[c(n-1)],...[c1]]

In [9]:
test2=np.arange(1,13).reshape(4,3)
print("\ntest",test2)

a10=np.flip(test2,axis=0)
print("\nflip axis 0",a10)

a11=np.flip(test2,axis=1)
print("\nflip axis 1",a11)

a12=np.transpose(test2)
print("\ntranspose",a12)


test [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

flip axis 0 [[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]

flip axis 1 [[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]

transpose [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


Reshape array

In [10]:
#a13=test.reshape(

if we give arr.reshape(dim,negative value) then the other dimension will be autocomputed by numpy

In [11]:
print("\n arrays:\n",test2.reshape(2,-1),"\n",test2.reshape(12,-1))


 arrays:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [12]:
print("\n arrays:\n",test2.reshape(-1,2),"\n",test2.reshape(-1,12))


 arrays:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]]


To flatten the matrix into one vector 
- reshape changes the original array with 
- ravel is a function that returns a view of the orignal 
- changes the orignal array

In [13]:
print(test2.reshape(12,))
print(np.ravel(test2))
print(test2.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


linspace : it arranges a range of array into equidistant elements
- start stop step are the values
- endpoint denotes if the endpoint is inclusive or not
- restep will display the gap between all elements

In [14]:
print(np.linspace(0,10,5))
print(np.linspace(0,10,5,endpoint=False))
print(np.linspace(0,10,5,retstep=True))
print(np.linspace(5,0,5,retstep=True))

print("Big array")
print(np.linspace(0,5,10000,retstep=True))  #will not display all elements

[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]
(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)
(array([5.  , 3.75, 2.5 , 1.25, 0.  ]), -1.25)
Big array
(array([0.00000000e+00, 5.00050005e-04, 1.00010001e-03, ...,
       4.99899990e+00, 4.99949995e+00, 5.00000000e+00]), 0.0005000500050005)


Random Function :<br>
probability mass function - discrete function<br>
probability density function - continous function<br>

In [15]:
print(int(np.random.random()*10))
print(np.random.random((2,3)))
print(np.random.random((2,3,4)))

1
[[0.25558207 0.56622673 0.82979286]
 [0.74474967 0.88041581 0.67748994]]
[[[0.57312115 0.2770213  0.50425875 0.52686567]
  [0.79802339 0.71256739 0.15996282 0.79294026]
  [0.06536791 0.60716089 0.82927914 0.7169688 ]]

 [[0.90540307 0.80616835 0.27444051 0.28737497]
  [0.26235661 0.39340622 0.63597678 0.02627271]
  [0.96655264 0.18856446 0.09856326 0.1749833 ]]]


#### Binomial distribution and Normal distribution of array 
**Binomial** : 
- takes n:trials
- takes p success rate
- take the no of occurence

**Normal**
- loc (centreness)
- scale (std)
- size of result


In [16]:
a=np.random.binomial(10000,0.5)
print(a)

b=np.random.normal(0,10,10)
print(b)

print(np.random.randint(0,10,10))
print(np.random.randint(0,10,(2,3)))

4946
[ 16.16103631  -4.90862802  -4.70221722   4.22860826   0.87901083
 -10.58590278   2.85223613   9.79112787  -0.43501775  -2.35693732]
[7 1 5 3 7 3 9 8 6 4]
[[0 2 8]
 [5 2 3]]


Row and column wise array elements operations

In [17]:
a=(np.random.randint(0,10,(2,3)))
print(a)
print("\nmin :",np.min(a))
print("row min :",np.min(a,axis=1)) #row wise
print("col min :",np.min(a,axis=0)) #column wise

print("\nmax :",np.max(a))
print("row max :",np.max(a,axis=1))
print("col max :",np.max(a,axis=0))

print("\nmean :",np.mean(a))
print("row mean :",np.mean(a,axis=1))
print("col mean :",np.mean(a,axis=0))

print("\nstd :",np.std(a))
print("row std :",np.std(a,axis=1))
print("col std :",np.std(a,axis=0))

print("\nsum :",np.sum(a))
print("row sum :",np.sum(a,axis=1))
print("col sum :",np.sum(a,axis=0))

[[3 4 1]
 [1 4 4]]

min : 1
row min : [1 1]
col min : [1 4 1]

max : 4
row max : [4 4]
col max : [3 4 4]

mean : 2.8333333333333335
row mean : [2.66666667 3.        ]
col mean : [2.  4.  2.5]

std : 1.3437096247164249
row std : [1.24721913 1.41421356]
col std : [1.  0.  1.5]

sum : 17
row sum : [8 9]
col sum : [4 8 5]


In [18]:
print(a)
print(np.argmax(a))
print(np.argmax(a,axis=1))
print(np.argmax(a,axis=0))


[[3 4 1]
 [1 4 4]]
1
[1 1]
[0 0 1]
