# NUMPY ARRAYS

In [2]:
import numpy as np

By convention, w'll find that most people in the SciPy/PyData world will
import NumPy using np as an alias:

In [3]:
arr = np.array([1,2,3,4,5]) #to create an array from python list.
arr #1D array

array([1, 2, 3, 4, 5])

In [4]:
lst = [1,2,3,4.5,6,8.9]
b = np.array(lst)
b

array([1. , 2. , 3. , 4.5, 6. , 8.9])

Its important to note that unlike Python lists, NumPy arrays can only contain data of the same
type. If the types do not match, NumPy will upcast them according to its type promo‐
tion rules; here, integers are upcast to floating point

Finally, unlike Python lists, which are always one-dimensional sequences, NumPy
arrays can be multidimensional. Here’s one way of initializing a multidimensional
array using a list of lists

In [5]:
a = np.array([[1,2,3],[4,5,6]])
a #2D array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([range(i,i+3) for i in [1,4,7]]) #nested list to create 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(a.shape)
print(a.ndim)
print(arr.shape)
print(arr.ndim)

(2, 3)
2
(5,)
1


.shape -> order of array in (n,m) fashion
.ndim -> dimension of the np array

In [8]:
print(b.dtype)
print(arr.dtype)
print(type(b))

float64
int32
<class 'numpy.ndarray'>


.dtype -> returns the data type of the array contents
type -> returns the class type

np.arange(x,y,z)-> elements from x to y-1 with or without step z

In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array.reshape(order)-> to give order or new shape to arrays

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## ARRAY BUILDER FUNCTIONS

#### np.zeros((shape),dtype) -> creates a zero matrix of desired shape ####

In [11]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### np.ones((shape),dtype) -> creates a one matrix of desired shape ####

In [12]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### np.eye(n,m,k,dtype)->creates identity matrix of desired MXN order, k value determines the diagonal offset ####


In [13]:
np.eye(5,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [14]:
np.eye(5,5,k=2,dtype=int)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.eye(4,5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

#### np.full((shape),value) -> makes a matrix of desired shape with desired values ####

In [16]:
np.full((3,4),1.2)

array([[1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2]])

#### np.empty((shape))-> creates a empty matrix with garbage value

In [17]:
np.empty((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.60218491e-306]])

## ARRAY OPERATIONS

### Diagonals

In [18]:
a1 = np.arange(12).reshape(4,-1)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

diag -> gives diagonal of the matrix and k value is taken as offset position 

In [19]:
print(np.diag(a1))
print(np.diag(a1,k=-1))
print(np.diag(a1,k=1)) 

[0 4 8]
[ 3  7 11]
[1 5]


### flipping

In [20]:
np.flip(a1)

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

flip -> first flips along left right direction then flips along up down direction

In [21]:
print(np.flip(a1,axis=0)) #along rows
print("\n")
print(np.flip(a1,axis=1)) #along columns

[[ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]]


[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


In [22]:
np.fliplr(a1)#flip the matrix along left right direction axis=1

array([[ 2,  1,  0],
       [ 5,  4,  3],
       [ 8,  7,  6],
       [11, 10,  9]])

In [23]:
np.flipud(a1)#flip the matrix along up down direction axis=0

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

USING NUMPY TO EXTRACT ALL POSSIBLE DIAGONALS IN ALL DIRECTION
[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]

In [24]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.diag(b)

array([1, 5, 9])

In [26]:
np.diag(np.flipud(b))

array([7, 5, 3])

In [27]:
np.diag(np.fliplr(b))

array([3, 5, 7])

In [28]:
np.diag(np.flip(b))

array([9, 5, 1])

--------------------------------------------------------------------------------------------------------------------------------------------------------------

In [29]:
c = np.arange(10).reshape(5,2)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
np.transpose(c)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [31]:
c = np.arange(9).reshape(3,3)
print(f'{a.flatten()} and {np.ravel(a)}') #negates all dimensions

[1 2 3 4 5 6] and [1 2 3 4 5 6]


## RANDOM GENERATION ##

In [32]:
np.random.random((3,3)) #creates a matrix with random float numbers

array([[0.67916442, 0.87143901, 0.59644237],
       [0.72476048, 0.58391847, 0.56938948],
       [0.69154264, 0.89445026, 0.25806133]])

In [33]:
r = np.random.randint(-5,5,(6,7))
r

array([[-4, -5,  2, -3, -4,  4,  4],
       [ 0, -2, -5,  0,  4, -4, -5],
       [ 0,  1, -5,  1, -2,  4, -1],
       [-2,  3, -3, -4, -5,  2,  3],
       [ 1,  2, -4, -2, -3, -1,  4],
       [ 1, -3, -2,  0,  3,  1,  4]])

In [34]:
a=np.random.randint(0,10,size=(4,3))
print(a)
print(np.sum(a))
print(np.min(a,axis=1))
print(np.min(a,axis=0))
print(np.max(a,axis=0))
print(np.max(a,axis=1))
print(np.std(a))
print(np.mean(a))
print(np.var(a))

[[8 9 1]
 [7 7 2]
 [3 6 6]
 [6 8 4]]
67
[1 2 3 4]
[3 6 1]
[8 9 6]
[9 7 6 8]
2.4309920243024705
5.583333333333333
5.909722222222224


In [35]:
print(np.argmax(r))

5


In [36]:
np.random.normal(0,0.1,size=(3,3))

array([[-0.07803069, -0.06441138, -0.06495955],
       [-0.25557804,  0.07608522,  0.05845391],
       [-0.05866388,  0.14379936, -0.0486114 ]])

In [37]:
# Parameters
n = 10000  # number of trials (coin tosses)
p = 0.5    # probability of success (getting a head)

# Perform the binomial experiment
number_of_heads = np.random.binomial(n, p)

print(f"Number of heads in {n} coin tosses: {number_of_heads}")

Number of heads in 10000 coin tosses: 5076


------------------------------------------------------------------------

## MATRIX OPERATIONS


### concatenation of 2 matrices

In [38]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
print(np.concatenate((a1,a2),axis=1)) # adds more columns i.e concatenates along the columns

[[ 0  1  2 11 12 13]
 [ 3  4  5 14 15 16]
 [ 6  7  8 17 18 19]]


In [39]:
a1 = np.arange(9).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
print(np.concatenate((a1,a2),axis=0)) # adds more rows i.e concatenates along the rows

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [40]:
print(np.vstack((a1,a2))) #takes 1 tuple as argument using 2 arrays same as axis  = 0

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [41]:
print(np.hstack((a1,a2))) #same as axis = 1

[[ 0  1  2 11 12 13]
 [ 3  4  5 14 15 16]
 [ 6  7  8 17 18 19]]


### Trigonometetric functions and log functions

In [42]:
a=np.array([0,30,60,90])
print(np.cos(a*np.pi/180))
print(np.tan(a*np.pi/180))
print(np.sin(a*np.pi/180))
print(np.log2(2))
print(np.log10(10))
print(np.log(10))

[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]
[0.        0.5       0.8660254 1.       ]
1.0
1.0
2.302585092994046


### Spliting and slicing


##### spliting

In [43]:
ar = np.arange(30).reshape(5,6)
ar

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
np.split(ar,(2,),axis=1) #splits along the direction of columns

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3,  4,  5],
        [ 8,  9, 10, 11],
        [14, 15, 16, 17],
        [20, 21, 22, 23],
        [26, 27, 28, 29]])]

In [45]:
np.split(ar,(2,)) #split along the direction of rows

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]])]

In [46]:
print(np.vsplit(ar,(2,))) #axis = 0
print("\n")
print(np.hsplit(ar,(2,))) #axis = 1

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])]


[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25]]), array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])]


##### slicing


Suppose a numpy array has of dim NXM, 
we can perfom slicing for each dimension
i.e a[row_slice, column_slice]

In [47]:
ar

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [48]:
#slice [[8 9][14 15]]
ar[1:3,2:4]

array([[ 8,  9],
       [14, 15]])

[[15, 16, 17],
[ 21, 22, 23],
[ 27, 28, 29]] splice this portion and find the sum of diagonals

In [49]:
a3 = ar[2:,3:]
a3

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [50]:
np.sum(np.diag(np.flipud(a3))+np.diag(a3)) #comprehensive way

132

In [52]:
x=np.diag(a3)
y=np.diag(np.flipud(a3))
print(np.diag(x))
print(np.flipud(np.diag(y)))
print(np.flipud(np.diag(y))+np.diag(x))
print(np.sum(np.flipud(np.diag(y))+np.diag(x))) #illustrative way

#print(np.flipud(np.diag(np.diag(np.flipud(a3))))+np.diag(np.diag(a3)))

[[15  0  0]
 [ 0 22  0]
 [ 0  0 29]]
[[ 0  0 17]
 [ 0 22  0]
 [27  0  0]]
[[15  0 17]
 [ 0 44  0]
 [27  0 29]]
132


NUMPY ARRAYS CAN BE TREATED AS VARIABLES AND CAN SUPPORT MATHEMATICAL AND LOGICAL OPERATIONS

In [52]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(21,30).reshape(3,3)

In [53]:
print("\n", a1, "\n\n", a2)
print("\n")
print(a1+2*a2)
print("\n")
print(a1*a2)
print("\n")
print(a1/a2)
print("\n")
print(a1.dot(a2)) #matrix multiplication


 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[21 22 23]
 [24 25 26]
 [27 28 29]]


[[43 46 49]
 [52 55 58]
 [61 64 67]]


[[ 21  44  69]
 [ 96 125 156]
 [189 224 261]]


[[0.04761905 0.09090909 0.13043478]
 [0.16666667 0.2        0.23076923]
 [0.25925926 0.28571429 0.31034483]]


[[150 156 162]
 [366 381 396]
 [582 606 630]]


In [98]:
a= np.random.randint(-5,6,(5,6))
a

array([[ 1,  1,  4, -3,  3, -3],
       [-4, -2,  3,  1, -5, -5],
       [-1,  3, -5,  4,  4,  2],
       [ 2, -2, -1,  5,  1,  2],
       [ 3,  2, -5, -4, -1,  1]])

In [100]:
print(a<0)
print()
print(a[a<0])
print()
print(a[(a%2==0) & (a>0)])
print()
print(a[(a%2==0) | ((a>2) & (a%2!=0) )])

[[False False False  True False  True]
 [ True  True False False  True  True]
 [ True False  True False False False]
 [False  True  True False False False]
 [False False  True  True  True False]]

[-3 -3 -4 -2 -5 -5 -1 -5 -2 -1 -5 -4 -1]

[4 4 4 2 2 2 2]

[ 4  3 -4 -2  3  3  4  4  2  2 -2  5  2  3  2 -4]
